Milestone: Members-Only
enkog/Members-Only pull request #1
Opened 2021-01-06 10:58 UTC by enkog

This project brings to light the practice of performing authentication and authorization using rails own gem called devise. 
I have employed the use of rails MVC structure to achieve this.

2021-01-06 13:09 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [ ] Couldnt run the app because of the error below.Check your migration file
````ruby
Caused by:
NameError: undefined local variable or method `t' for #<AddUserIdToPosts:0x000055ff5956f4d8>

````
# \[OPTIONAL\] 

* [ ] A helper method to check if user is signed_in? can be handy here

```ruby
# must be a helper method to be used in views
helper_method :signed_in?
def signed_in?
  !current_user.nil?
end
```
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2021-01-06 21:30 UTC, Temmarie requested changes
## Changes Required! :recycle:

### Hi @enkog   ! :wave: :wave:

#### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.


**Recommended**

- [x] Just like the previous TSE, I, unfortunately, could not run your project due to the error below, please check your migration file.

**Caused by:
NoMethodError: undefined method `add_references' for #<AddUserIdToPosts:0x00007fffd5d90c88>**


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2021-01-07 08:17 UTC, peterrobert requested changes
### CHANGES REQUIRED ♻️ ⏹️ 

Hello, @enkog nice progress you are almost there 👍🏿 . However, there are a few changes that need to be made before we can continue. Kindly check below ⬇️ 

- [x] There should be sign in and sign out links present in your application. At the moment I had to directly type the weblinks in the browser. Kindly add some navigation. 
![sign_in_out_link_requirement](https://user-images.githubusercontent.com/32361963/103866647-242c3600-50d7-11eb-8d5c-951fd0caefb7.png)

- [x] A user should be able to sign out. At the moment there is no way for a user to sign out. This can all be solved if you include links to your application.

![sign_out_requirement](https://user-images.githubusercontent.com/32361963/103867011-b5031180-50d7-11eb-8ca7-7491178892c4.png)

- [ ] As a guest user, you can only see post's text. Kindly fix this too. I can see that you have restricted this in your controller 👍🏿 , however, in your views I have no way of knowing this. This will all be solved if you have some navigation in your application.

![guest_can_see_only_posts_requirement](https://user-images.githubusercontent.com/32361963/103867467-7ae63f80-50d8-11eb-87e5-2770a42bba0b.png)

- [ ] In your application helper, you need to define the below method ⬇️ 

`def signed_in_only!
  redirect_to  new_user_session_path unless current_user
end
`
This will check if it is the current_user.

### if you have any question kindly reach me via slack @peterrobert

### HAPPY CODING 💻

2021-01-07 08:17 UTC, peterrobert commented on config/routes.rb
>  end
### [OPTIONAL]
This is a very good practice: Kindly add root route. When a user visits your application it is good to have a root route other than being redirected to the default " your on rails"  template

Use this [article](https://curriculum.railsbridge.org/intro-to-rails/setting_the_default_page) to learn more about this.

2021-01-07 16:32 UTC, BrittanyBlake approved these changes
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****


 Good Luck and Happy Coding! 🍀 👩🏾‍💻

2021-01-07 16:55 UTC, merged